# Generated by Django 5.2 on 2025-05-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_remove_product_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_available",
        ),
    ]
